- hosts: localhost
  tasks:
    - kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: kube-playbook-test
            namespace: playground
          data:
            key: value
